/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "s21_test.check" instead.
 */

#include "s21_SmartCalc.h"

#include <check.h>

#define ERROR 1
#define OK 0
#define TOL 1e-7

START_TEST(test_error_1) {
  double result = 0;
  char input[] = "sin((0.5)";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_2) {
  double result = 0;
  char input[] = "cos(0.5))";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_3) {
  double result = 0;
  char input[] = "00.5+1";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_4) {
  double result = 0;
  char input[] = "0.43546.436+43654=";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_5) {
  double result = 0;
  char input[] = "sin((0.5)";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_6) {
  double result = 0;
  char input[] = "213324-0000345";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_7) {
  double result = 0;
  char input[] = "5435sin(0.342)";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_8) {
  double result = 0;
  char input[] = "5xxxxx";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_9) {
  double result = 0;
  char input[] = "sin(x5)=";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_10) {
  double result = 0;
  char input[] = "5++53463=";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_11) {
  double result = 0;
  char input[] = "13*674//468";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_12) {
  double result = 0;
  char input[] = "2535-35)=";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_13) {
  double result = 0;
  char input[] = "()";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_14) {
  double result = 0;
  char input[] = "tan(0.5)+(2542*23)+";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_15) {
  double result = 0;
  char input[] = "log3553";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_16) {
  double result = 0;
  char input[] = "log(24)(";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_17) {
  double result = 0;
  char input[] = "sq(254)";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_18) {
  double result = 0;
  char input[] = "sqart(53243)=";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_19) {
  double result = 0;
  char input[] = "sqrt(2))))";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_20) {
  double result = 0;
  char input[] = "+*/";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_21) {
  double result = 0;
  char input[] = "424+*3574";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_22) {
  double result = 0;
  char input[] = "tavghvffv(3)";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_23) {
  double result = 0;
  char input[] = "tan()";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_24) {
  double result = 0;
  char input[] = "acos";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_25) {
  double result = 0;
  char input[] = "asin8923-2342";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_26) {
  double result = 0;
  char input[] = "ln";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_27) {
  double result = 0;
  char input[] = "ln646";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_28) {
  double result = 0;
  char input[] = "zwerwesfg";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_29) {
  double result = 0;
  char input[] = "4324mod*";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_30) {
  double result = 0;
  char input[] = ")345+353(";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_31) {
  double result = 0;
  char input[] = "24234+.*46";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_32) {
  double result = 0;
  char input[] = "57+567mos25";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_33) {
  double result = 0;
  char input[] = "cod(435)";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_34) {
  double result = 0;
  char input[] =
      "111111111111111111111111111111111111111111111111111111111111111111111111"
      "111111111111111111111111111111111111111111111111111111111111111111111111"
      "111111111111111111111111111111111111111111111111111111111111111111111111"
      "1111111111111111111111111111111111";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_35) {
  double result = 0;
  char input[] = "234/0+12123^3=";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_36) {
  double result = 0;
  char input[] = "433353.431mod0=";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_37) {
  double result = 0;
  char input[] = "acos(213)+sin(123)=";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_38) {
  double result = 0;
  char input[] = "asin(-213)=";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_39) {
  double result = 0;
  char input[] = "log(-25335)=";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_40) {
  double result = 0;
  char input[] = "ln(-213)=";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_error_41) {
  double result = 0;
  char input[] = "sqrt(-213)=";
  ck_assert_int_eq(Smart_calc(input, &result, 0), ERROR);
}
END_TEST

START_TEST(test_1) {
  double result = 0;
  char input[] = "1+1=";
  double cntrl = 1 + 1;
  int is_error = Smart_calc(input, &result, 0);
  ck_assert_int_eq(is_error, OK);
  ck_assert_double_eq_tol(result, cntrl, TOL);
}
END_TEST

START_TEST(test_2) {
  double result = 0;
  char input[] = "135354-345234+35345=";
  double cntrl = 135354 - 345234 + 35345;
  int is_error = Smart_calc(input, &result, 0);
  ck_assert_int_eq(is_error, OK);
  ck_assert_double_eq_tol(result, cntrl, TOL);
}
END_TEST

START_TEST(test_3) {
  double result = 0;
  char input[] = "1231.532+235-341.324+13433-123.324=";
  double cntrl = 1231.532 + 235 - 341.324 + 13433 - 123.324;
  int is_error = Smart_calc(input, &result, 0);
  ck_assert_int_eq(is_error, OK);
  ck_assert_double_eq_tol(result, cntrl, TOL);
}
END_TEST

START_TEST(test_4) {
  double result = 0;
  char input[] = "213*1434.7432/3421=";
  double cntrl = 213 * 1434.7432 / 3421;
  int is_error = Smart_calc(input, &result, 0);
  ck_assert_int_eq(is_error, OK);
  ck_assert_double_eq_tol(result, cntrl, TOL);
}
END_TEST

START_TEST(test_5) {
  double result = 0;
  char input[] = "42423^(-12)=";
  double cntrl = pow(42423, -12);
  int is_error = Smart_calc(input, &result, 0);
  ck_assert_int_eq(is_error, OK);
  ck_assert_double_eq_tol(result, cntrl, TOL);
}
END_TEST

START_TEST(test_6) {
  double result = 0;
  char input[] = "213.1231^5=";
  double cntrl = pow(213.1231, 5);
  int is_error = Smart_calc(input, &result, 0);
  ck_assert_int_eq(is_error, OK);
  ck_assert_double_eq_tol(result, cntrl, TOL);
}
END_TEST

START_TEST(test_7) {
  double result = 0;
  char input[] = "43245mod241=";
  double cntrl = fmod(43245, 241);
  int is_error = Smart_calc(input, &result, 0);
  ck_assert_int_eq(is_error, OK);
  ck_assert_double_eq_tol(result, cntrl, TOL);
}
END_TEST

START_TEST(test_8) {
  double result = 0;
  char input[] = "8529.8483mod234.54=";
  double cntrl = fmod(8529.8483, 234.54);
  int is_error = Smart_calc(input, &result, 0);
  ck_assert_int_eq(is_error, OK);
  ck_assert_double_eq_tol(result, cntrl, TOL);
}
END_TEST

START_TEST(test_9) {
  double result = 0;
  char input[] = "(352+252)/254=";
  double cntrl = (352.0 + 252.0) / 254.0;
  int is_error = Smart_calc(input, &result, 0);
  ck_assert_int_eq(is_error, OK);
  ck_assert_double_eq_tol(result, cntrl, TOL);
}
END_TEST

START_TEST(test_10) {
  double result = 0;
  char input[] = "234+(95-328*(242+2342/2344))=";
  double cntrl = 234.0 + (95.0 - 328.0 * (242.0 + 2342.0 / 2344.0));
  int is_error = Smart_calc(input, &result, 0);
  ck_assert_int_eq(is_error, OK);
  ck_assert_double_eq_tol(result, cntrl, TOL);
}
END_TEST

START_TEST(test_11) {
  double result = 0;
  char input[] = "25.0+39.0=";
  double cntrl = 25.0 + 39.0;
  int is_error = Smart_calc(input, &result, 0);
  ck_assert_int_eq(is_error, OK);
  ck_assert_double_eq_tol(result, cntrl, TOL);
}
END_TEST

START_TEST(test_12) {
  double result = 0;
  char input[] = "sin(324^(-235))=";
  double cntrl = sin(pow(324, -235));
  int is_error = Smart_calc(input, &result, 0);
  ck_assert_int_eq(is_error, OK);
  ck_assert_double_eq_tol(result, cntrl, TOL);
}
END_TEST

START_TEST(test_13) {
  double result = 0;
  char input[] = "cos(-234)=";
  double cntrl = cos(-234);
  int is_error = Smart_calc(input, &result, 0);
  ck_assert_int_eq(is_error, OK);
  ck_assert_double_eq_tol(result, cntrl, TOL);
}
END_TEST

START_TEST(test_14) {
  double result = 0;
  char input[] = "tan(0.2342)=";
  double cntrl = tan(0.2342);
  int is_error = Smart_calc(input, &result, 0);
  ck_assert_int_eq(is_error, OK);
  ck_assert_double_eq_tol(result, cntrl, TOL);
}
END_TEST

START_TEST(test_15) {
  double result = 0;
  char input[] = "atan(0.2342)=";
  double cntrl = atan(0.2342);
  int is_error = Smart_calc(input, &result, 0);
  ck_assert_int_eq(is_error, OK);
  ck_assert_double_eq_tol(result, cntrl, TOL);
}
END_TEST

START_TEST(test_16) {
  double result = 0;
  char input[] = "asin(0.2342)=";
  double cntrl = asin(0.2342);
  int is_error = Smart_calc(input, &result, 0);
  ck_assert_int_eq(is_error, OK);
  ck_assert_double_eq_tol(result, cntrl, TOL);
}
END_TEST

START_TEST(test_17) {
  double result = 0;
  char input[] = "acos(0.2342)=";
  double cntrl = acos(0.2342);
  int is_error = Smart_calc(input, &result, 0);
  ck_assert_int_eq(is_error, OK);
  ck_assert_double_eq_tol(result, cntrl, TOL);
}
END_TEST

START_TEST(test_18) {
  double result = 0;
  char input[] = "acos(0.2342)+sin(0.94)-acos(0.123)+ln(28+45)=";
  double cntrl = acos(0.2342) + sin(0.94) - acos(0.123) + log(28.0 + 45.0);
  int is_error = Smart_calc(input, &result, 0);
  ck_assert_int_eq(is_error, OK);
  ck_assert_double_eq_tol(result, cntrl, TOL);
}
END_TEST

START_TEST(test_19) {
  double result = 0;
  char input[] = "log(143+3431^(-13))+ln(234mod34)=";
  double cntrl = log10(143 + pow(3431, -13)) + log(fmod(234, 34));
  int is_error = Smart_calc(input, &result, 0);
  ck_assert_int_eq(is_error, OK);
  ck_assert_double_eq_tol(result, cntrl, TOL);
}
END_TEST

START_TEST(test_20) {
  double result = 0;
  char input[] = "sqrt(234793)/sin(243)=";
  double cntrl = sqrt(234793) / sin(243);
  int is_error = Smart_calc(input, &result, 0);
  ck_assert_int_eq(is_error, OK);
  ck_assert_double_eq_tol(result, cntrl, TOL);
}
END_TEST

START_TEST(test_21) {
  double result = 0;
  double x = 10;
  char input[] = "sqrt(23)/sin(x)=";
  double cntrl = sqrt(23) / sin(10);
  int is_error = Smart_calc(input, &result, x);
  ck_assert_int_eq(is_error, OK);
  ck_assert_double_eq_tol(result, cntrl, TOL);
}
END_TEST

START_TEST(test_22) {
  double result = 0;
  double x = 0.9437;
  char input[] = "sin(x)*cos(x)=";
  double cntrl = sin(0.9437) * cos(0.9437);
  int is_error = Smart_calc(input, &result, x);
  ck_assert_int_eq(is_error, OK);
  ck_assert_double_eq_tol(result, cntrl, TOL);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, test_error_1);
  tcase_add_test(tc1_1, test_error_2);
  tcase_add_test(tc1_1, test_error_3);
  tcase_add_test(tc1_1, test_error_4);
  tcase_add_test(tc1_1, test_error_5);
  tcase_add_test(tc1_1, test_error_6);
  tcase_add_test(tc1_1, test_error_7);
  tcase_add_test(tc1_1, test_error_8);
  tcase_add_test(tc1_1, test_error_9);
  tcase_add_test(tc1_1, test_error_10);
  tcase_add_test(tc1_1, test_error_11);
  tcase_add_test(tc1_1, test_error_12);
  tcase_add_test(tc1_1, test_error_13);
  tcase_add_test(tc1_1, test_error_14);
  tcase_add_test(tc1_1, test_error_15);
  tcase_add_test(tc1_1, test_error_16);
  tcase_add_test(tc1_1, test_error_17);
  tcase_add_test(tc1_1, test_error_18);
  tcase_add_test(tc1_1, test_error_19);
  tcase_add_test(tc1_1, test_error_20);
  tcase_add_test(tc1_1, test_error_21);
  tcase_add_test(tc1_1, test_error_22);
  tcase_add_test(tc1_1, test_error_23);
  tcase_add_test(tc1_1, test_error_24);
  tcase_add_test(tc1_1, test_error_25);
  tcase_add_test(tc1_1, test_error_26);
  tcase_add_test(tc1_1, test_error_27);
  tcase_add_test(tc1_1, test_error_28);
  tcase_add_test(tc1_1, test_error_29);
  tcase_add_test(tc1_1, test_error_30);
  tcase_add_test(tc1_1, test_error_31);
  tcase_add_test(tc1_1, test_error_32);
  tcase_add_test(tc1_1, test_error_33);
  tcase_add_test(tc1_1, test_error_34);
  tcase_add_test(tc1_1, test_error_35);
  tcase_add_test(tc1_1, test_error_36);
  tcase_add_test(tc1_1, test_error_37);
  tcase_add_test(tc1_1, test_error_38);
  tcase_add_test(tc1_1, test_error_39);
  tcase_add_test(tc1_1, test_error_40);
  tcase_add_test(tc1_1, test_error_41);
  tcase_add_test(tc1_1, test_1);
  tcase_add_test(tc1_1, test_2);
  tcase_add_test(tc1_1, test_3);
  tcase_add_test(tc1_1, test_4);
  tcase_add_test(tc1_1, test_5);
  tcase_add_test(tc1_1, test_6);
  tcase_add_test(tc1_1, test_7);
  tcase_add_test(tc1_1, test_8);
  tcase_add_test(tc1_1, test_9);
  tcase_add_test(tc1_1, test_10);
  tcase_add_test(tc1_1, test_11);
  tcase_add_test(tc1_1, test_12);
  tcase_add_test(tc1_1, test_13);
  tcase_add_test(tc1_1, test_14);
  tcase_add_test(tc1_1, test_15);
  tcase_add_test(tc1_1, test_16);
  tcase_add_test(tc1_1, test_17);
  tcase_add_test(tc1_1, test_18);
  tcase_add_test(tc1_1, test_19);
  tcase_add_test(tc1_1, test_20);
  tcase_add_test(tc1_1, test_21);
  tcase_add_test(tc1_1, test_22);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
